### ISSUE TITLE
Create profile layout page

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#41]
**Branch:** `profile-layout`

### Task at Hand
1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?node-id=296%3A764&t=ZUYXanuqiGjFSMxf-1).
2. Implement the following components:
    <br>
    ```
    Avatar.tsx
    Banner.tsx
    ProfileTemplate.tsx
    ```
3. Implement the following pages:
    <br>
    ```
    profile.tsx
    ```
2. Confirm that your code and pull request follow the [Pull Request Checklist](https://h4i.notion.site/Pull-Request-Checklist-37c67d3b6a9b488f8339f32116bfb12c).

### Acceptance Criteria
- [x] Create a responsive template for the Profile page
- [x] Implement the Profile page

**Comment by Y1chenYao** [comment]
After studying the mid-fi as well as attempting the code base (finishing avatar component), I have 2 clarifying questions:
1. I searched for banner design in [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?node-id=296%3A764&t=ZUYXanuqiGjFSMxf-1) but I don't think I can find it. 🤔️ I imagine it to be like MUI alerts as well as cookie banners? 
2. ProfileTemplate.jsx: I feel like this is highly dependent upon atoms (button, textfield) and molecules (navbar, profileform). I think other pairs are implementing them so I am curious about the general workflow for this.

Would really appreciate it you if respond before Monday. Thank you! 🥺

**Comment by jasozh** [comment]
1. The banner is just the rectangle with the user avatar component attached to it.
2. For `ProfileTemplate`, treat each of the required components as a black box. While developing it, you can just use gray-colored rectangles to represent the banner and the form itself. Once that's done, you'll need to replace the rectangles with components as props, and the actual `Profile` page just calls `ProfileTemplate` with props passed in.

The ticket is intentionally a bit vague since it's a lot easier to explain in-person than through text, so feel free to wait until Tuesday before starting work. Check the Figma [here](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?node-id=545-5283&t=U46X1Ab9hS09acTu-0), I added a section for `Profile` which should help clarify things.
